name: build-release
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read|write
      actions: read|write
      checks: read|write
      deployments: read|write
      id-token: read|write
      issues: read|write
      discussions: read|write
      packages: read|write
      pages: read|write
      pull-requests: read|write
      repository-projects: read|write
      security-events: read|write
      statuses: read|write
    steps:
      - uses: actions/checkout@v3
      
      - name: version
        id: version
        run: echo "::set-output name=version::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: resume.tex
          args: -jobname=kyle-vickers-resume -output-format=pdf
      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: kyle-vickers-resume
          path: kyle-vickers-resume.pdf
      - name: generate tag variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.vars.outputs.sha_short }}
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kyle-vickers-resume.zip
          asset_name: kyle-vickers-resume.zip
          asset_content_type: application/zip
      - name: Upload resume to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: z0mi3ie/resume
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ github.token }}
          file: kyle-vickers-resume
          asset_name: kyle-vickers-resume
          tag: ${{ github.ref }}
          overwrite: true
          body: "Upload release asset"
