name: build-release
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      checks: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v3

      - name: version
        id: version
        run: echo "version=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: generate tag variables
        id: vars
        shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: resume.tex
          args: -jobname=kyle-vickers-resume -output-format=pdf

      - name: check permissions
        id: perm
        shell: bash
        run: |
          ls -al kyle-vickers-resume.pdf
          whoami
          sudo chown runner kyle-vickers-resume.pdf
          ls -al kyle-vickers-resume.pdf

      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: kyle-vickers-resume
          path: kyle-vickers-resume.pdf


      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.version }}
          tag_name: ${{ env.sha_short }}

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: kyle-vickers-resume

      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/resume/resume/build/kyle-vickers-resume.zip
          asset_name: kyle-vickers-resume.zip
          asset_content_type: application/zip

      - name: Upload resume to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: z0mi3ie/resume
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ github.token }}
          file: kyle-vickers-resume
          asset_name: kyle-vickers-resume
          tag: ${{ github.ref }}
          overwrite: true
          body: "Upload release asset"
