name: build-release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: resume.tex
          args: -jobname=kyle-vickers-resume -output-format=pdf

      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: kyle-vickers-resume
          path: kyle-vickers-resume.pdf

      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          body: "A .pdf of the resume is attached to this release."
          artifacts: "kyle-vickers-resume.pdf"
